---
title: "giang_exploreData"
author: "Giang"
date: "2024-07-17"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

library(tidyverse)
library(ggplot2) 
library(dplyr)
library(gtsummary)
library(rsample)

setwd("C:/Users/giang/OneDrive/Desktop/data_science_COSMOS/myopia")

my_data <- read.csv("data/myopia_org.csv", head = TRUE, sep = ";")

glimpse(my_data)

```

```{r}

class(my_data$MYOPIC)
unique(my_data$MYOPIC)

my_data <- my_data %>% 
  mutate(myopic = MYOPIC)

my_data <- my_data %>% 
  mutate(mommy_int = as.integer(MOMMY), dadmy_int = as.integer(DADMY))
glimpse(my_data)

my_data <- my_data %>% 
  mutate(MYOPIC = case_when(MYOPIC == 1 ~ "Yes", 
                            MYOPIC == 0 ~ "No"))

my_data <- my_data %>% 
  mutate(GENDER = case_when(GENDER == 1 ~ "M", 
                            GENDER == 0 ~ "F"))

my_data <- my_data %>% 
  mutate(MOMMY = case_when(MOMMY == 1 ~ "Yes", 
                           MOMMY == 0 ~ "No"))
my_data <- my_data %>% 
  mutate(DADMY = case_when(DADMY == 1 ~ "Yes", 
                           DADMY == 0 ~ "No"))

my_data <- my_data %>% 
  mutate(MYOPIC = as.factor(MYOPIC), GENDER = as.factor(GENDER), 
         MOMMY = as.factor(MOMMY), DADMY = as.factor(DADMY))
         
glimpse(my_data)

```

```{r}

my_data <- my_data %>% 
  mutate(PARENTS = mommy_int + dadmy_int) %>% 
  mutate(parents_int = as.integer(PARENTS))

my_data <- my_data %>% 
  mutate(PARENTS = case_when(PARENTS == 0 ~ "neither myopic",
                            PARENTS == 1 ~ "one myopic",
                            PARENTS == 2 ~ "both myopic"))
my_data <- my_data %>% 
  mutate(PARENTS = as.factor(PARENTS)) %>% 
    mutate(PARENTS=fct_relevel(PARENTS,c("neither myopic","one myopic","both myopic")))

levels(my_data$PARENTS)

glimpse(my_data)
```

```{r}

ggplot(data = my_data, 
       aes(x = MOMMY, 
           fill = MYOPIC)) + 
  geom_bar() +
  labs(x = "Mother's Myopic Status", 
       fill = "Participant's Myopic Status") 

```

```{r}

ggplot(data = my_data, 
       aes(x = DADMY, 
           fill = MYOPIC)) + 
  geom_bar() +
  labs(x = "Father's Myopic Status", 
       fill = "Participant's Myopic Status")

```

```{r}

#find percentages of each to compare 

ggplot(data = my_data, 
       aes(x = PARENTS, 
           fill = MYOPIC)) + 
  geom_bar(position = "dodge") + 
  labs(x = "Parents' Myopic Status", 
       fill = "Participant's Myopic Status")

parents_table <- table(my_data$MYOPIC, my_data$PARENTS)
parents_table

chisq.test(parents_table)

```

```{r}

library(dplyr)

PARENTS <- my_data$PARENTS
MYOPIC <- my_data$MYOPIC
par_df <- data.frame(PARENTS, MYOPIC)

conditionNM <- "neither myopic"
conditionOM <- "one myopic"
conditionBM <- "both myopic"
conditionY <- "Yes"
conditionN <- "No"
total_count <- nrow(par_df)

NM_N_df <- par_df %>% 
  filter(PARENTS == conditionNM & MYOPIC == conditionN)
filter_NM_N <- nrow(NM_N_df)
percentage_NM_N <- ((filter_NM_N / total_count) * 100)
  round(percentage_NM_N, 2)
#23.79

OM_N_df <- par_df%>% 
  filter(PARENTS == conditionOM & MYOPIC == conditionN)
filter_OM_N <- nrow(OM_N_df)
percentage_OM_N <- ((filter_OM_N / total_count) * 100)
  round(percentage_OM_N, 2)
#43.69

BM_N_df <- par_df%>% 
  filter(PARENTS == conditionBM & MYOPIC == conditionN)
filter_BM_N <- nrow(BM_N_df)
percentage_BM_N <- ((filter_BM_N / total_count) * 100)
  round(percentage_BM_N, 2)
#19.42
  
NM_Y_df <- par_df %>% 
  filter(PARENTS == conditionNM & MYOPIC == conditionY)
filter_NM_Y <- nrow(NM_Y_df)
percentage_NM_Y <- ((filter_NM_Y / total_count) * 100)
  round(percentage_NM_Y, 2)
#0.81
  
OM_Y_df <- par_df%>% 
  filter(PARENTS == conditionOM & MYOPIC == conditionY)
filter_OM_Y <- nrow(OM_Y_df)
percentage_OM_Y <- ((filter_OM_Y / total_count) * 100)
  round(percentage_OM_Y, 2)
#6.63
  
BM_Y_df <- par_df%>% 
  filter(PARENTS == conditionBM & MYOPIC == conditionY)
filter_BM_Y <- nrow(BM_Y_df)
percentage_BM_Y <- ((filter_BM_Y / total_count) * 100)
  round(percentage_BM_Y, 2)
#5.66

``` 

```{r}

str(my_data$myopic)

log_model <- glm(myopic ~ PARENTS, data = my_data)
summary(log_model)

glm(myopic ~ PARENTS, data = my_data) %>% 
  tbl_regression(estimate_fun = function(x) style_number(x, digits = 3), exponentiate = TRUE)

set.seed(0)
data_split <- initial_split(my_data, prop = 0.7) 
train_data <- training(data_split)
test_data <- testing(data_split)

log_model2 <- glm(myopic ~ PARENTS, data = my_data)
summary(log_model2)

glm(myopic ~ PARENTS, data = my_data) %>% 
  tbl_regression(estimate_fun = function(x) style_number(x, digits = 3), exponentiate = TRUE)

pred_prob <- (log_model2) %>% 
  predict(test_data,type="response")
print(pred_prob)

predicted.classes <- ifelse(pred_prob > 0.5, "1", "0")
mean(predicted.classes == test_data$myopic)

```




